server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8

spring:
  datasource:
    url: jdbc:sqlserver://web-finals-server.database.windows.net:1433;database=web-final;user=postgres@web-finals-server;password=!WEBfinal!;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
